# https://matthewpalmer.net/kubernetes-app-developer/articles/kubernetes-apiversion-definition-guide.html
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backstage-svc
  namespace: mybi-cloud
  labels:
    app: backstage-svc
spec:
  replicas: 1
  minReadySeconds: 60
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: backstage-svc
        env: dev
    spec:
      imagePullSecrets:
        - name: registry-secret
      containers:
        - name: backstage-svc
          image: harbor.test.mybi.cn/mybi-cloud/backstage-svc:v1.0.0
          imagePullPolicy: Always
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: dev
          ports:
            - containerPort: 8001
          volumeMounts:
            - name: time-config
              mountPath: /etc/localtime
      volumes:
        - name: time-config
          hostPath:
            path: /usr/share/zoneinfo/Asia/Shanghai
  selector:
    matchLabels:
      app: backstage-svc

---
apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mybi-cloud
spec:
  selector:
    app: backstage-svc
    env: dev
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  #    nodePort: 30003
  #  type: NodePort
  clusterIP: None